-- WHICH EDITION HAD THE BIGGEST FEMALE PARTICIPATION?
-- QUAL EDIÇÃO TEVE A MAIOR PATICIPAÇÃO FEMININA?

SELECT Games,
       COUNT(Name) AS total_athletes,
       SUM(CASE WHEN Sex = 'F' THEN 1 ELSE 0 END) AS total_women,
       (SUM(CASE WHEN Sex = 'F' THEN 1 ELSE 0 END) / COUNT(*) * 100) AS perc_women
FROM olympics.athlete_events
GROUP BY Games
ORDER BY total_women DESC;

-- WHICH FEMALE ATHETE HAS THE HIGHTEST NUMBER OF PARTICIPATIONS?
-- QUAL ATLETA FEMININA TEM O MAIOR NÚMERO DE PARTICIPAÇÕES?

SELECT Name, Team, count(DISTINCT Games) AS total_participations
FROM olympics.athlete_events
WHERE Sex LIKE 'F'
GROUP BY Name, Team
ORDER BY total_participations DESC
LIMIT 10;

-- WHICH MALE ATHETE HAS THE HIGHTEST NUMBER OF PARTICIPATIONS?
-- QUAL ATLETA MASCULINO TEM O MAIOR NÚMERO DE PARTICIPAÇÕES?

SELECT Name, Team, count(DISTINCT Games) AS total_participations
FROM olympics.athlete_events
WHERE Sex LIKE 'M'
GROUP BY Name, Team
ORDER BY total_participations DESC
LIMIT 10;

--WHO WAS THE OLDEST PERSON TO COMPETE?
--QUEM FOI A PESSOA MAIS VELHA A COMPETIR?

SELECT Name, Team, Games,CAST(Age AS INT) AS Age_num
FROM olympics.athlete_events
WHERE Age NOT LIKE 'NA'
GROUP BY Name, Team, Games, Age
ORDER BY Age DESC
LIMIT 10;

--WHO WAS THE YOUNGEST PERSON TO COMPETE?
--QUEM FOI A PESSOA MAIS NOVA A COMPETIR?

SELECT Name, Team, Games,CAST(Age AS INT) AS Age_num
FROM olympics.athlete_events
WHERE Age NOT LIKE 'NA'
GROUP BY Name, Team, Games, Age
ORDER BY Age
LIMIT 10;

--HOW DID THE NUMBER OF EVENTS IN THE SUMMER GAMES EVOLVED IN TIME?
--COMO O NÚMERO DE MODALIDADES DAS OLIMÍADAS DE VERÃO EVOLUIU COM O TEMPO?

SELECT count(DISTINCT Event) AS total_events, Games
FROM olympics.athlete_events
WHERE Games LIKE '%Summer'
GROUP BY Games
ORDER BY Games;

--HOW DID THE NUMBER OF EVENTS IN THE WINTER GAMES EVOLVED IN TIME?
--COMO O NÚMERO DE MODALIDADES DAS OLIMÍADAS DE INVERNO EVOLUIU COM O TEMPO?

SELECT count(DISTINCT Event) AS total_events, Games
FROM olympics.athlete_events
WHERE Games LIKE '%Winter'
GROUP BY Games
ORDER BY Games;

--WHAT IS THE SPORT WITH THE BIGGEST FEMALE PARTICIPATION?
--QUAL  É O ESPORTE COM A MAIOR PARTICIPAÇÃO FEMININA?

SELECT Sport, count(Sport) AS female_participation
FROM olympics.athlete_events
WHERE Sex LIKE 'F'
GROUP BY Sport
ORDER BY female_participation DESC
LIMIT 10;

--WHICH SPORT HAS THE HIGHEST AVERAGE HIGHT?
--QUAL ESPORTE TEM A MAIOR MÉDIA DE ALTURA?

SELECT Sport, ROUND (AVG(CAST(Height AS INT64)), 2) AS avg_height
FROM olympics.athlete_events
WHERE Height != 'NA'
GROUP BY Sport
ORDER BY avg_height DESC
LIMIT 10;

--WHICH SPORT HAS THE LOWEST AVERAGE HIGHT?
--QUAL ESPORTE TEM A MENOR MÉDIA DE ALTURA?

SELECT Sport, ROUND (AVG(CAST(Height AS INT64)), 2) AS avg_height
FROM olympics.athlete_events
WHERE Height != 'NA'
GROUP BY Sport
ORDER BY avg_height
LIMIT 10;

--TOTAL MEDAL NUMBER BY COUNTRY IN SUMMER ATHLETIC COMPETITIONS
--NÚMERO TOTAL DE MEDALHAS POR PAÍS EM MODALIDADES ESPORTIVAS DE VERÃO

SELECT
  t2.region,
  SUM(CASE WHEN t1.Medal = 'Gold' THEN 1 ELSE 0 END) AS total_gold_medals,
  SUM(CASE WHEN t1.Medal = 'Silver' THEN 1 ELSE 0 END) AS total_silver_medals,
  SUM(CASE WHEN t1.Medal = 'Bronze' THEN 1 ELSE 0 END) AS total_bronze_medals
FROM olympics.athlete_events AS t1
INNER JOIN `projeto-01-403615.olympics.noc_regions` AS t2 ON t1.NOC = t2.NOC
WHERE Season LIKE 'Summer' AND Sport NOT LIKE 'Art Competitions'
GROUP BY t2.region
ORDER BY total_gold_medals DESC
LIMIT 10;

--EXPLORING ART COMPETITIONS: Games and Events
--EXPLORANDO COMPERTIÇÕES ARTÍSTICAS: Edições e Modalidades

SELECT Games, Event
FROM olympics.athlete_events
WHERE Sport LIKE 'Art Competitions'
GROUP BY Event, Games
ORDER BY Games;

--EXPLORING ART COMPETITIONS: Artists
--EXPLORANDO COMPERTIÇÕES ARTÍSTICAS: Artistas

SELECT COUNT(DISTINCT Name) AS total_artists, Sex, Team, Year
FROM olympics.athlete_events
WHERE Sport LIKE 'Art Competitions'
GROUP BY Year, Team, Sex
ORDER BY Year;

